"""
Stage 3: Lead Discovery

Supabase-level dedup guard prevents duplicate pipeline runs across
Streamlit Cloud workers (pipeline_status = 'discovering' check).

Three channels run in parallel:

  Channel A — Formal Platforms (direct_leads table)
    A1: Apify LinkedIn Jobs Scraper  (actor: hKByXkMQaC5Qt9UMN)
        Input: generated LinkedIn search URLs — one per role group.
        Returns job poster name + LinkedIn URL (hiring manager).

    A2: Apify Wellfound Scraper      (actor: sqkHGNG0toRTR3ORV)
        Input: ONE Wellfound URL (free-tier redirects all role-specific
        URLs to /location/india — so multiple calls waste CUs).

    A3: YC Jobs via HTTP (workatastartup.com)
        No API key needed — direct HTTP scrape.

  Channel B — Hidden Signals (indirect_leads table)
    B1: Apify LinkedIn Post Search Scraper  (actor: buIWk2uOUzTmcLsuB)
        Input: "#Hiring {role}" search phrases generated by Stage 2.
        Gemini extracts company + role from each post in batches of 8.

  DECOMMISSIONED:
    - Cutshort (Tavily search) — permanently down, 432 errors.
    - Tavily enrichment (stage lookup, hiring managers) — disabled.

Three-layer deduplication:
    Layer 1: job ID / signal_url dedup within each channel
    Layer 2: rapidfuzz cross-channel dedup (85% company + 80% role title)
    Layer 3: Supabase upsert on_conflict when persisting

Output: direct leads written to direct_leads table, indirect to indirect_leads table.
        Match placeholder records created in matches table for Stage 4 to score.
"""
import os
import re
import logging
from typing import Optional
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.parse import urlencode
from dotenv import load_dotenv
from pydantic import BaseModel, Field

from models.leads import RawLead
from utils.helpers import is_duplicate, chunk_list

load_dotenv()
log = logging.getLogger(__name__)

APIFY_API_KEY  = os.getenv("APIFY_API_KEY", "")
MAX_RAW_LEADS  = int(os.getenv("MAX_RAW_LEADS", "50"))

# If at least this many raw jobs are collected across all channels, proceed to
# ranking even if some channels are still failing or slow.
PARTIAL_RESULT_THRESHOLD = int(os.getenv("PARTIAL_RESULT_THRESHOLD", "250"))

# Set by discover_leads() — app.py reads this to show a partial-success banner.
discovery_partial: bool = False

# Apify actor IDs
_ACTOR_LINKEDIN_JOBS  = "hKByXkMQaC5Qt9UMN"
_ACTOR_WELLFOUND      = "sqkHGNG0toRTR3ORV"   # clearpath/wellfound-api-ppe
_ACTOR_LINKEDIN_POSTS = "buIWk2uOUzTmcLsuB"

# No Tavily throttle needed — Tavily is permanently disabled (432 errors).

# Known MNCs / public companies — skip Tavily enrichment, assign stage directly
_KNOWN_MNC: set[str] = {
    "amazon", "apple", "google", "microsoft", "meta", "netflix",
    "swiggy", "zomato", "flipkart", "meesho", "paytm", "phonepe",
    "reliance", "reliance retail", "reliance industries",
    "tata", "tcs", "tata consultancy services", "infosys", "wipro",
    "hcl", "hcl technologies", "tech mahindra", "l&t", "ltimindtree",
    "hdfc", "hdfc bank", "icici", "icici bank", "idfc first bank",
    "axis bank", "kotak mahindra bank", "sbi", "state bank of india",
    "aditya birla", "aditya birla capital", "aditya birla group",
    "itc", "itc limited", "itc hotels limited",
    "unilever", "hindustan unilever", "p&g", "nestle", "britannia",
    "accenture", "ibm", "deloitte", "pwc", "kpmg", "ey",
    "spotify", "adobe", "salesforce", "oracle", "sap",
    "vedantu", "byju's", "unacademy", "upgrad",
    "taskus", "concentrix", "teleperformance",
    "sgs", "the lubrizol corporation", "lubrizol",
    "forbidden foods", "forbidden foods (brb popped chips)",
}

def _is_mnc(company: str) -> bool:
    """Return True if company is a known large company — skip Tavily lookup."""
    return company.lower().strip() in _KNOWN_MNC

# ── Public entry point ────────────────────────────────────────────

def discover_leads(
    candidate_id: str,
    search_queries: dict,
    candidate_model=None,   # CandidateModel — used for pre-scoring before the cap
) -> tuple[list[RawLead], list[RawLead]]:
    """
    Discover raw job leads for a candidate.

    Supabase-level dedup guard: checks pipeline_status in the DB before
    launching actors. If status is already 'discovering', returns immediately.
    This works across multiple Streamlit processes (unlike threading.Lock).

    ALL channels run FULLY IN PARALLEL via ThreadPoolExecutor:
      - LinkedIn Direct: one actor call per role group (primary title + aliases)
      - LinkedIn Indirect: one actor call for all hidden_signals combined
      - Wellfound: ONE actor call total (all URLs redirect to /location/india)
      - YC Jobs: concurrent HTTP scrape (no API key needed)
    """
    from db.queries import update_candidate_status, get_candidate

    # ── Supabase-level dedup guard ────────────────────────────────────────────
    # Prevents duplicate pipeline runs across Streamlit Cloud workers.
    # Covers ALL in-progress statuses so the gap between 'discovering' → 
    # 'discovered' → 'ranking' cannot be exploited by a rerender.
    existing = get_candidate(candidate_id)
    current_status = existing.get("pipeline_status") if existing else None
    if current_status in ("discovering", "discovered", "ranking", "ranked"):
        log.warning(
            "S3: BLOCKED — candidate %s already has status '%s'. Skipping duplicate run.",
            candidate_id, current_status,
        )
        return [], []

    update_candidate_status(candidate_id, "discovering")
    log.info("S3: Starting lead discovery for candidate %s", candidate_id)

    # Parse role_groups (new format) or fall back to formal_platforms (legacy)
    role_groups_raw = search_queries.get("role_groups", [])
    hidden_queries  = search_queries.get("hidden_signals", [])

    if role_groups_raw:
        groups = role_groups_raw
    else:
        # Legacy: wrap each primary title as a single-title group
        groups = [
            {"role_title": q, "search_titles": [q], "hidden_signals": []}
            for q in search_queries.get("formal_platforms", [])
        ]

    log.info("S3: %d role groups: %s",
             len(groups), [g.get("role_title") for g in groups])

    if not APIFY_API_KEY:
        log.warning("S3: APIFY_API_KEY not set — skipping all Apify channels")
        return [], []

    # Assemble parallel task list: (label, fn, args)
    tasks: list[tuple[str, object, tuple]] = []

    # LinkedIn Direct — one actor call per role group
    for g in groups:
        title         = g.get("role_title", "unknown")
        search_titles = g.get("search_titles") or [title]
        tasks.append((
            f"LinkedIn Direct [{title}]",
            _run_linkedin_jobs_group,
            (search_titles, title),
        ))

    # Wellfound — ONE actor call PER role_title (exact title, not aliases)
    # Each role title gets its own Wellfound search URL so we cover all job types.
    for g in groups:
        title = g.get("role_title", "")
        if title:
            tasks.append((
                f"Wellfound [{title}]",
                _run_wellfound_channel,
                ([title],),   # one URL built from the exact role_title
            ))

    # LinkedIn Indirect — all hidden_signals in one call
    all_hidden = list(hidden_queries)
    for g in groups:
        all_hidden.extend(g.get("hidden_signals") or [])
    all_hidden = list(dict.fromkeys(all_hidden))
    if all_hidden:
        tasks.append(("LinkedIn Indirect", _run_apify_post_scraper_channel, (all_hidden,)))

    # YC Jobs (Cutshort removed — Tavily is permanently dead, 432 errors)
    if all_primary:
        tasks.append(("YC Jobs", _run_yc_jobs_channel, (all_primary,)))

    # Execute all tasks in parallel
    direct_leads:   list[RawLead] = []
    indirect_leads: list[RawLead] = []
    failed_channels: list[str]    = []

    global discovery_partial
    discovery_partial = False

    log.info("S3: Launching %d parallel scrape tasks simultaneously", len(tasks))
    with ThreadPoolExecutor(max_workers=max(len(tasks), 1)) as executor:
        future_map = {
            executor.submit(fn, *args): label
            for label, fn, args in tasks
        }
        for future in as_completed(future_map):
            label = future_map[future]
            try:
                results: list[RawLead] = future.result()
                if "Indirect" in label:
                    indirect_leads.extend(results)
                else:
                    direct_leads.extend(results)
                total_so_far = len(direct_leads) + len(indirect_leads)
                log.info("S3: ✅ %-45s → %d leads  (running total: %d)",
                         label, len(results), total_so_far)
            except Exception as exc:
                total_so_far = len(direct_leads) + len(indirect_leads)
                failed_channels.append(label)
                if total_so_far >= PARTIAL_RESULT_THRESHOLD:
                    # We already have enough — demote failure to a warning
                    log.warning(
                        "S3: ⚠ %-45s → FAILED (ignored — %d leads already collected): %s",
                        label, total_so_far, exc,
                    )
                else:
                    log.error("S3: ❌ %-45s → FAILED: %s", label, exc)

    total_raw = len(direct_leads) + len(indirect_leads)

    if failed_channels and total_raw >= PARTIAL_RESULT_THRESHOLD:
        discovery_partial = True
        log.warning(
            "S3: Partial result mode — %d leads collected, %d channel(s) failed: %s",
            total_raw, len(failed_channels), failed_channels,
        )
    elif failed_channels:
        log.warning(
            "S3: %d channel(s) failed and only %d leads collected (below threshold %d). "
            "Proceeding anyway.",
            len(failed_channels), total_raw, PARTIAL_RESULT_THRESHOLD,
        )

    # Enrich + dedup
    if direct_leads:
        direct_leads = _enrich_company_stages(direct_leads)
        direct_leads = _enrich_hiring_managers(direct_leads)

    direct_leads   = _dedup_within(direct_leads)
    indirect_leads = _dedup_within(indirect_leads)
    direct_leads, indirect_leads = _dedup_cross_channel(direct_leads, indirect_leads)


    # ── Pre-score and sort direct leads (best-first ordering) ────────────────
    # No hard cap — ALL scraped leads go to the DB.
    # Pre-scoring keeps the highest-quality leads ordered first so Stage 4
    # sees the best candidates when it fetches from the matches table.
    if direct_leads and candidate_model is not None:
        try:
            from pipeline.s4_rank import _score_direct_initial
            scored_pairs = []
            for lead in direct_leads:
                match_dict = {
                    "role_title":            lead.role_title,
                    "company_name":          lead.company_name,
                    "company_stage_label":   lead.company_stage_label,
                    "description":           lead.description,
                    "compensation_estimate": lead.compensation_estimate,
                    "posted_at":             lead.posted_at,
                }
                prescore, _ = _score_direct_initial(match_dict, candidate_model)
                scored_pairs.append((prescore, lead))
            scored_pairs.sort(key=lambda x: x[0], reverse=True)
            direct_leads = [lead for _, lead in scored_pairs]
            log.info(
                "S3: Pre-scored %d direct leads — top: %.2f | bottom: %.2f — ALL going to DB",
                len(direct_leads),
                scored_pairs[0][0] if scored_pairs else 0,
                scored_pairs[-1][0] if scored_pairs else 0,
            )
        except Exception as e:
            log.warning("S3: Pre-scoring failed (%s) — leads kept in scrape order", e)

    log.info("S3: Final — %d direct + %d indirect leads — ALL being persisted to DB",
             len(direct_leads), len(indirect_leads))

    _persist_leads(candidate_id, direct_leads, indirect_leads)
    update_candidate_status(candidate_id, "discovered")

    return direct_leads, indirect_leads




# ── URL builders ──────────────────────────────────────────────────────────────

def _build_linkedin_jobs_url(role_title: str, location: str = "India") -> str:
    """Build a LinkedIn Jobs search URL for a given role title."""
    params = {"keywords": role_title, "location": location, "position": 1, "pageNum": 0}
    return "https://www.linkedin.com/jobs/search/?" + urlencode(params)


# Wellfound only has category pages for broad role families.
# Niche titles (Chief of Staff, Growth Manager) return 0 results — map to valid slugs.
_WELLFOUND_SLUG_MAP: dict[str, str] = {
    "chief of staff":           "operations",
    "founder's office":         "operations",
    "founders office":          "operations",
    "strategic initiatives":    "operations",
    "business manager to ceo":  "operations",
    "special projects manager": "operations",
    "operations manager":       "operations",
    "head of operations":       "operations",
    "growth manager":           "marketing",
    "growth lead":              "marketing",
    "growth hacker":            "marketing",
    "growth marketing manager": "marketing",
    "product growth":           "marketing",
    "business development manager": "business-development",
    "partnerships manager":     "business-development",
}


def _build_wellfound_url(role_title: str, country: str = "india") -> str:
    """Build a Wellfound role+location URL. Maps niche titles to valid category slugs."""
    key  = role_title.lower().strip()
    slug = _WELLFOUND_SLUG_MAP.get(key) or re.sub(r"[^a-z0-9]+", "-", key).strip("-")
    return f"https://wellfound.com/role/l/{slug}/{country}"




# ── Channel A1b: LinkedIn Jobs — Role-Group Aware (─────────────────────

def _run_linkedin_jobs_group(search_titles: list[str], role_label: str) -> list[RawLead]:
    """
    Run Apify LinkedIn Jobs Scraper for ONE role group.
    Sends all titles (primary + aliases) as separate URLs in a SINGLE actor call.
    Returns up to 100 leads (reduced from 200 since aliases improve precision).

    Logs include the role_label so every actor run is traceable:
      [LinkedIn Direct [Chief of Staff]] runId:abc RUNNING
      [LinkedIn Direct [Chief of Staff]] runId:abc COMPLETE → 73 leads
    """
    try:
        from apify_client import ApifyClient
        client = ApifyClient(APIFY_API_KEY)
    except ImportError:
        log.error("S3[A1][%s]: apify-client not installed", role_label)
        return []

    unique_titles = list(dict.fromkeys(search_titles))
    urls = [_build_linkedin_jobs_url(t) for t in unique_titles]
    seen_job_ids: set[str] = set()
    leads: list[RawLead] = []

    log.info("S3[A1][%s]: Sending %d URLs to LinkedIn Jobs actor: %s",
             role_label, len(urls), unique_titles)
    try:
        run = client.actor(_ACTOR_LINKEDIN_JOBS).call(
            run_input={
                "urls":          urls,
                "count":         100,   # 100 per group (3 groups = 300 total max)
                "scrapeCompany": True,
            }
        )
        run_id = (run or {}).get("id", "?")
        items  = list(client.dataset(run["defaultDatasetId"]).iterate_items())
        log.info("S3[A1][%s]: runId:%s returned %d raw items",
                 role_label, run_id, len(items))

        for item in items:
            job_id = str(item.get("id", ""))
            if job_id and job_id in seen_job_ids:
                continue
            if job_id:
                seen_job_ids.add(job_id)
            lead = _parse_apify_linkedin_job(item)
            if lead:
                leads.append(lead)

    except Exception as e:
        log.error("S3[A1][%s]: Actor FAILED: %s", role_label, e)

    return leads

# ── Channel A1: Apify LinkedIn Jobs Scraper ───────────────────────────────────

def _run_linkedin_jobs_channel(queries: list[str]) -> list[RawLead]:
    """
    Run Apify LinkedIn Jobs Scraper.
    Queries are deduplicated and chunked into sets of max 4 URLs per actor call.
    Each query becomes a LinkedIn search URL. Returns hiring manager data.
    """
    try:
        from apify_client import ApifyClient
        client = ApifyClient(APIFY_API_KEY)
    except ImportError:
        log.error("S3[A1]: apify-client not installed")
        return []

    from utils.helpers import chunk_list
    unique_queries = list(dict.fromkeys(queries))
    urls = [_build_linkedin_jobs_url(q) for q in unique_queries]
    seen_job_ids: set[str] = set()
    leads: list[RawLead] = []

    # Send all URLs in a SINGLE actor call.
    # Stage 2 produces max 3 role titles, so this is always a small list.
    # Chunking caused duplicate actor runs when the same queries appeared
    # across multiple pipeline re-renders.
    if not urls:
        return leads

    try:
        run = client.actor(_ACTOR_LINKEDIN_JOBS).call(
            run_input={
                "urls":          urls,
                "count":         100,   # reduced: role_groups approach gives better precision
                "scrapeCompany": True,  # needed to get company data
            }
        )
        items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
        log.debug("S3[A1]: Actor returned %d raw items", len(items))

        for item in items:
            job_id = str(item.get("id", ""))
            if job_id and job_id in seen_job_ids:
                continue
            if job_id:
                seen_job_ids.add(job_id)
                lead = _parse_apify_linkedin_job(item)
                if lead:
                    leads.append(lead)

    except Exception as e:
        log.error("S3[A1]: Apify LinkedIn Jobs actor failed: %s", e)

    return leads


def _parse_apify_linkedin_job(item: dict) -> Optional[RawLead]:
    """Parse a raw Apify LinkedIn Jobs item into a RawLead."""
    try:
        company = item.get("companyName", "")
        role    = item.get("title", "")
        if not company or not role:
            return None

        salary_info = item.get("salaryInfo", [])
        salary_str  = " – ".join(salary_info) if salary_info else None

        return RawLead(
            company_name             = company,
            role_title               = role,
            description              = item.get("descriptionText", "")[:2000],
            key_requirements         = _extract_requirements(item.get("descriptionText", "")),
            location                 = item.get("location", "India"),
            remote_ok                = "remote" in item.get("location", "").lower(),
            compensation_estimate    = salary_str,
            source_channel           = "formal",
            source_platform          = "LinkedIn Jobs",
            post_url                 = item.get("link"),
            posted_at                = _parse_date(item.get("postedAt")),
            apify_job_id             = str(item.get("id", "")),
            hiring_manager_name      = item.get("jobPosterName"),
            hiring_manager_linkedin  = item.get("jobPosterProfileUrl"),
            company_stage_label      = None,   # enriched by _enrich_company_stages
        )
    except Exception as e:
        log.warning("S3[A1]: Failed to parse item: %s", e)
        return None


# ── Channel A2: Apify Wellfound Scraper ───────────────────────────────────────

def _run_wellfound_channel(queries: list[str]) -> list[RawLead]:
    """
    Run Apify Wellfound Scraper (clearpath/wellfound-api-ppe).
    Queries are deduplicated and chunked into sets of max 4 URLs per actor call.
    Each query becomes a Wellfound role URL.
    Returns full description + salary. No hiring contact from Wellfound.
    """
    try:
        from apify_client import ApifyClient
        client = ApifyClient(APIFY_API_KEY)
    except ImportError:
        log.error("S3[A2]: apify-client not installed")
        return []

    from utils.helpers import chunk_list
    unique_queries = list(dict.fromkeys(queries))
    urls = [_build_wellfound_url(q) for q in unique_queries]
    leads: list[RawLead] = []

    for url_chunk in chunk_list(urls, 1):
        try:
            run = client.actor(_ACTOR_WELLFOUND).call(
                run_input={
                    "urls":           url_chunk,
                    "pageLimit":      3,
                    "onlyRemoteJobs": False,
                    "sortBy":         "LAST_POSTED",
                }
            )
            items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
            log.debug("S3[A2]: Wellfound actor returned %d raw items for chunk", len(items))

            for item in items:
                lead = _parse_apify_wellfound_job(item, unique_queries)
                if lead:
                    leads.append(lead)

        except Exception as e:
            log.error("S3[A2]: Apify Wellfound actor failed for chunk: %s", e)

    return leads


def _parse_apify_wellfound_job(
    item: dict,
    target_queries: list[str] | None = None,
) -> Optional[RawLead]:
    """Parse a raw Apify Wellfound item into a RawLead.

    Filters:
    - Skips listings older than 90 days (MongoDB-style stale roles).
    - Skips roles whose title doesn't fuzzy-match any target query (irrelevant
      titles like Engineering Manager, CSM that Wellfound bundles in).
    """
    try:
        company_name = item.get("company_name", "")
        role_title   = item.get("title", "")
        if not company_name or not role_title:
            return None

        # ── Date filter: skip listings older than 90 days ─────────────────────
        live_start = item.get("live_start_at")
        if live_start:
            posted_at = datetime.fromtimestamp(live_start, tz=timezone.utc)
            if (datetime.now(timezone.utc) - posted_at).days > 90:
                log.debug("S3[A2]: Skipping '%s @ %s' — older than 90 days", role_title, company_name)
                return None
        else:
            posted_at = None

        # ── Relevance filter: skip roles far from target titles ───────────────
        if target_queries:
            from rapidfuzz import fuzz
            best = max(
                fuzz.partial_ratio(role_title.lower(), q.lower())
                for q in target_queries
            )
            if best < 55:
                log.debug("S3[A2]: Skipping '%s' — relevance %.0f < 55 vs queries", role_title, best)
                return None

        locations = item.get("location_names", [])
        location  = locations[0] if locations else "India"

        return RawLead(
            company_name             = company_name,
            role_title               = role_title,
            description              = item.get("description", "")[:2000],
            key_requirements         = _extract_requirements(item.get("description", "")),
            location                 = location,
            remote_ok                = bool(item.get("remote", False)),
            compensation_estimate    = item.get("compensation") or None,
            source_channel           = "formal",
            source_platform          = "Wellfound",
            post_url                 = item.get("url"),
            posted_at                = posted_at,
            apify_job_id             = str(item.get("id", "")),
            hiring_manager_name      = None,
            hiring_manager_linkedin  = None,
            company_stage_label      = "unknown",
        )
    except Exception as e:
        log.warning("S3[A2]: Failed to parse Wellfound item: %s", e)
        return None


# ── Channel A3: Y Combinator Jobs (workatastartup.com) ───────────────────────
# Direct HTTP — no API key needed. The site uses Next.js and embeds all job
# data server-side in __NEXT_DATA__, so a plain requests.get() returns full JSON.

_YC_ROLE_SLUG_MAP: dict[str, str] = {
    "product manager":           "product-manager",
    "chief of staff":            "operations",
    "founder's office":          "operations",
    "founders office":           "operations",
    "operations manager":        "operations",
    "head of operations":        "operations",
    "strategic initiatives":     "operations",
    "business manager to ceo":   "operations",
    "special projects manager":  "operations",
    "growth manager":            "marketing",
    "growth lead":               "marketing",
    "growth hacker":             "marketing",
    "growth marketing manager":  "marketing",
    "business development manager": "business-development",
    "partnerships manager":      "business-development",
}


def _run_yc_jobs_channel(queries: list[str]) -> list[RawLead]:
    """
    Fetch YC Jobs from workatastartup.com via direct HTTP.
    No API key needed — public server-rendered pages, full JSON embedded in HTML.
    Deduplicates by job ID across all role slugs.
    """
    import requests
    import json
    import re as _re

    role_slugs: set[str] = set()
    for q in queries:
        key  = q.lower().strip()
        slug = _YC_ROLE_SLUG_MAP.get(key) or _re.sub(r"[^a-z0-9]+", "-", key).strip("-")
        role_slugs.add(slug)

    all_jobs: list[dict] = []
    seen_ids: set[str]   = set()
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
    }

    for slug in role_slugs:
        try:
            url  = f"https://www.workatastartup.com/jobs?role={slug}&country=IN"
            resp = requests.get(url, headers=headers, timeout=20)
            if resp.status_code != 200:
                log.warning("S3[A3]: YC Jobs HTTP %d for slug '%s'", resp.status_code, slug)
                continue

            # Extract server-side rendered Next.js data
            m = _re.search(
                r'<script id="__NEXT_DATA__"[^>]*>(.*?)</script>',
                resp.text, _re.DOTALL,
            )
            if not m:
                log.warning("S3[A3]: YC Jobs — __NEXT_DATA__ not found for slug '%s'", slug)
                continue

            page_props = json.loads(m.group(1)).get("props", {}).get("pageProps", {})

            # Try common key names — the site has used several across versions
            jobs = (
                page_props.get("jobs")
                or page_props.get("initialJobs")
                or page_props.get("jobListings")
                or page_props.get("startupJobs")
                or []
            )

            added = 0
            for job in jobs:
                jid = str(job.get("id", ""))
                if jid and jid in seen_ids:
                    continue
                if jid:
                    seen_ids.add(jid)
                all_jobs.append(job)
                added += 1

            log.debug("S3[A3]: YC Jobs slug '%s' → %d jobs", slug, added)

        except Exception as e:
            log.warning("S3[A3]: YC Jobs fetch failed for slug '%s': %s", slug, e)

    leads = [l for l in (_parse_yc_job(j) for j in all_jobs) if l]
    log.info("S3[A3]: YC Jobs → %d leads", len(leads))
    return leads


def _parse_yc_job(job: dict) -> Optional[RawLead]:
    """Parse a single YC Jobs job dict into a RawLead."""
    try:
        title = job.get("title") or job.get("role_title") or ""
        company_obj = job.get("company") or {}
        company = (
            company_obj.get("name")
            if isinstance(company_obj, dict)
            else job.get("company_name", "")
        ) or ""
        if not title or not company:
            return None

        desc   = (job.get("description") or job.get("job_description") or "")[:2000]
        job_id = str(job.get("id", ""))

        return RawLead(
            company_name             = company,
            role_title               = title,
            description              = desc,
            key_requirements         = _extract_requirements(desc),
            location                 = "India",
            remote_ok                = str(job.get("location_type", "")).upper() == "REMOTE",
            source_channel           = "formal",
            source_platform          = "YC Jobs",
            post_url                 = f"https://www.workatastartup.com/jobs/{job_id}" if job_id else None,
            posted_at                = _parse_date(job.get("created_at") or job.get("posted_at")),
            apify_job_id             = job_id,
            hiring_manager_name      = None,
            hiring_manager_linkedin  = None,
            company_stage_label      = None,
        )
    except Exception as e:
        log.warning("S3[A3]: Failed to parse YC job: %s", e)
        return None


# ── Channel A4: Cutshort.io — DECOMMISSIONED ─────────────────────────────────
# Removed: Cutshort relied on Tavily search, which is permanently down (432
# errors since 2026-05-18). The channel was producing zero leads and only
# generating error noise. If a new search provider is wired in, this channel
# can be rebuilt from scratch.


# ── Hiring Manager Enrichment (leads without LinkedIn contact) ────────────────

class _ManagerResult(BaseModel):
    name:         str | None = Field(
        default=None,
        description="Full name of the CEO, Founder, or relevant hiring manager. Null if not found."
    )
    linkedin_url: str | None = Field(
        default=None,
        description="LinkedIn profile URL (linkedin.com/in/...). Null if not found."
    )


def _enrich_hiring_managers(leads: list[RawLead]) -> list[RawLead]:
    """
    Hiring manager enrichment via Tavily — DISABLED.
    Tavily is out of credits (432 errors). Returns leads unchanged.
    LinkedIn Jobs leads already carry hiring manager data from Apify directly.
    """
    log.info("S3: Hiring manager enrichment skipped — Tavily disabled.")
    return leads


# ── Channel A — Company Stage Enrichment (all direct leads) ──────────────────

class _StageExtract(BaseModel):
    stage_label: str = Field(
        description="Company funding stage. Must be exactly one of: "
                    "pre_seed | seed | series_a | series_b | series_c | "
                    "late_stage | public | mnc | unknown"
    )


def _enrich_company_stages(leads: list[RawLead]) -> list[RawLead]:
    """
    Company stage enrichment via Tavily — DISABLED.
    Tavily is out of credits (432 errors). Returns leads unchanged.
    All leads will carry 'unknown' stage label until a new enrichment
    source (e.g. Crunchbase, static map) is wired in.
    """
    log.info("S3[A]: Stage enrichment skipped — Tavily disabled. %d leads carry 'unknown' stage.", len(leads))
    return leads


# ── Channel B: Apify LinkedIn Post Scraper ────────────────────────────────────

class _PostExtract(BaseModel):
    company_name:          str  = Field(description="Company name mentioned in post. Empty string if unclear.")
    role_title:            str  = Field(description="Job title or inferred role. E.g. 'Chief of Staff'. Empty string if not a hiring post.")
    role_inferred:         bool = Field(description="True if role was inferred from context, not explicitly stated.")
    extraction_confidence: str  = Field(description="'high' | 'medium' | 'low'")
    is_hiring_signal:      bool = Field(description="True ONLY if this is a genuine hiring post or announcement.")

class _PostExtractBatch(BaseModel):
    results: list[_PostExtract]


_POST_EXTRACT_SYSTEM = """You are a recruitment signal parser. Given LinkedIn post text, determine if it is a genuine hiring signal and extract structured data.

RULES:
- is_hiring_signal = true only if someone is actively hiring RIGHT NOW.
- role_title: if they say 'need a killer operator to run everything', infer 'Chief of Staff' or 'Head of Operations'.
- company_name: extract from post text. If the author works at a company, use that.
- extraction_confidence: 'high' if explicit, 'medium' if inferred, 'low' if very uncertain.
- If is_hiring_signal = false, set company_name and role_title to empty strings.

Return JSON: {"results": [{...one per post...}]}"""


def _run_apify_post_scraper_channel(queries: list[str]) -> list[RawLead]:
    """
    Run Apify LinkedIn Post Search Scraper for hidden hiring signals.
    All #Hiring search queries submitted in one actor call.
    Gemini extracts company + role from each post in batches of 8.
    """
    try:
        from apify_client import ApifyClient
        client = ApifyClient(APIFY_API_KEY)
    except ImportError:
        log.error("S3[B]: apify-client not installed")
        return []

    raw_posts: list[dict] = []
    seen_urls: set[str]   = set()

    # Append "India" to each query so results are India-focused.
    # Also set postType to JOBS to filter out non-hiring posts.
    india_queries = [
        q if "india" in q.lower() else f"{q} India"
        for q in queries
    ]

    try:
        run = client.actor(_ACTOR_LINKEDIN_POSTS).call(
            run_input={
                "searchQueries": india_queries,
                "maxPosts":      30,
                "postedLimit":   "week",
                "sortBy":        "date",
                "postType":      "JOBS",
            }
        )
        items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
        log.debug("S3[B]: Post Scraper returned %d raw posts", len(items))

        for item in items:
            url = (item.get("linkedinUrl") or "").strip()
            if not url or url in seen_urls:
                continue
            seen_urls.add(url)
            raw_posts.append(item)

    except Exception as e:
        log.error("S3[B]: Apify LinkedIn Post Scraper failed: %s", e)
        return []

    if not raw_posts:
        return []

    log.info("S3[B]: %d unique posts — extracting structured data via Gemini", len(raw_posts))
    return _extract_posts_to_leads(raw_posts)


def _extract_posts_to_leads(posts: list[dict]) -> list[RawLead]:
    """
    Use Gemini to extract company_name and role_title from LinkedIn post text.
    Processes in batches of 8. hiring_manager data comes from Apify post author — reliable.
    """
    from utils.gemini import gemini_json

    leads: list[RawLead] = []

    for batch in chunk_list(posts, 8):
        batch_text = "\n\n".join(
            f"[{i}] Author: {_get_author_name(p) or 'Company page'}\n"
            f"    Posted: {_get_posted_date_str(p)}\n"
            f"    Job card title: {(p.get('job') or {}).get('title', 'none')}\n"
            f"    Text: {p.get('content', '')[:500]}"
            for i, p in enumerate(batch)
        )

        try:
            extraction = gemini_json(
                prompt=f"Extract hiring signals from these LinkedIn posts:\n\n{batch_text}",
                system=_POST_EXTRACT_SYSTEM,
                schema=_PostExtractBatch,
            )
        except Exception as e:
            log.error("S3[B]: Gemini post extraction failed: %s", e)
            continue

        for i, result in enumerate(extraction.results):
            if not result.is_hiring_signal:
                continue
            if not result.company_name and not result.role_title:
                continue

            post = batch[i] if i < len(batch) else {}

            # engagement is now a nested object: {"likes": N, "comments": N, "shares": N}
            engagement = post.get("engagement", {})
            likes      = engagement.get("likes", 0) or 0
            comments   = engagement.get("comments", 0) or 0

            # postedAt is a nested object: {"date": "ISO string", "timestamp": ms, ...}
            posted_at_raw = post.get("postedAt", {})
            posted_at = _parse_date(
                posted_at_raw.get("date") if isinstance(posted_at_raw, dict) else posted_at_raw
            )

            lead = RawLead(
                company_name             = result.company_name or "Unknown",
                role_title               = result.role_title or "Unknown Role",
                description              = post.get("content", ""),
                key_requirements         = [],
                location                 = "India",
                remote_ok                = False,
                source_channel           = "hidden",
                source_platform          = "LinkedIn Post",
                post_url                 = post.get("linkedinUrl") or post.get("url"),
                posted_at                = posted_at,
                hiring_manager_name      = _get_author_name(post),
                hiring_manager_linkedin  = _get_author_linkedin(post),
                company_stage_label      = None,
            )
            # Attach indirect-specific fields used by _persist_leads → upsert_indirect_lead
            lead.__dict__["_engagement_score"]     = likes + comments
            lead.__dict__["_role_inferred"]         = result.role_inferred
            lead.__dict__["_extraction_confidence"] = result.extraction_confidence
            leads.append(lead)

    log.info("S3[B]: Gemini extracted %d valid hiring signals from %d posts",
             len(leads), len(posts))
    return leads


# ── Cross-channel deduplication ───────────────────────────────────────────────

def _dedup_within(leads: list[RawLead]) -> list[RawLead]:
    """Remove duplicates within a single channel using rapidfuzz."""
    seen: list[dict] = []
    unique: list[RawLead] = []
    for lead in leads:
        entry = {"company_name": lead.company_name, "role_title": lead.role_title}
        if not is_duplicate(entry, seen):
            unique.append(lead)
            seen.append(entry)
    return unique


def _dedup_cross_channel(
    direct: list[RawLead],
    indirect: list[RawLead],
) -> tuple[list[RawLead], list[RawLead]]:
    """
    Remove cross-channel duplicates. Direct leads take priority.
    Any indirect lead that matches a direct lead (same company + role) is dropped.
    """
    direct_index = [
        {"company_name": l.company_name, "role_title": l.role_title}
        for l in direct
    ]
    filtered_indirect = []
    dropped = 0
    for lead in indirect:
        entry = {"company_name": lead.company_name, "role_title": lead.role_title}
        if is_duplicate(entry, direct_index):
            dropped += 1
        else:
            filtered_indirect.append(lead)

    log.debug("S3: Cross-channel dedup: %d indirect leads dropped as duplicates of direct", dropped)
    return direct, filtered_indirect


# ── Persist to Supabase ───────────────────────────────────────────────────────

def _persist_leads(
    candidate_id: str,
    direct_leads: list[RawLead],
    indirect_leads: list[RawLead],
):
    """
    Write direct leads to direct_leads table and indirect leads to indirect_leads table.
    Creates placeholder match records for Stage 4 to score.
    Layer 3 dedup: upsert on_conflict prevents duplicate rows.
    """
    from db.queries import (
        upsert_direct_lead,
        upsert_indirect_lead,
        create_match_direct,
        create_match_indirect,
    )

    for lead in direct_leads:
        try:
            # mode='json' converts datetime objects to ISO strings — required for Supabase
            lead_id = upsert_direct_lead(lead.model_dump(mode='json'))
            lead.job_id = lead_id
            create_match_direct(candidate_id, lead_id)
        except Exception as e:
            import traceback
            log.error("S3: Failed to persist direct lead '%s @ %s': %s\n%s",
                      lead.role_title, lead.company_name, e, traceback.format_exc())

    for lead in indirect_leads:
        # Skip indirect leads with no URL — signal_url is the dedup key,
        # empty string would collapse all URL-less leads into one row
        if not lead.post_url:
            log.warning("S3: Skipping indirect lead '%s @ %s' — no post_url for dedup",
                        lead.role_title, lead.company_name)
            continue
        try:
            indirect_data = {
                **lead.model_dump(mode='json'),  # datetime → ISO string
                "signal_url":             lead.post_url,
                "snippet":                lead.description,
                "engagement_score":       lead.__dict__.get("_engagement_score", 0),
                "role_inferred":          lead.__dict__.get("_role_inferred", False),
                "extraction_confidence":  lead.__dict__.get("_extraction_confidence", "medium"),
            }
            lead_id = upsert_indirect_lead(indirect_data)
            lead.job_id = lead_id
            create_match_indirect(candidate_id, lead_id)
        except Exception as e:
            import traceback
            log.error("S3: Failed to persist indirect lead '%s @ %s': %s\n%s",
                      lead.role_title, lead.company_name, e, traceback.format_exc())


# ── Helper utilities ──────────────────────────────────────────────────────────

def _parse_date(value) -> Optional[datetime]:
    """Parse a date string or timestamp into a datetime. Returns None on failure."""
    if value is None:
        return None
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except Exception:
        return None


def _get_posted_date_str(post: dict) -> str:
    """Extract a readable posted date string from a post dict."""
    posted_at = post.get("postedAt", {})
    if isinstance(posted_at, dict):
        return posted_at.get("date") or posted_at.get("postedAgoText", "unknown")
    return str(posted_at) if posted_at else "unknown"


def _get_author_name(post: dict) -> Optional[str]:
    """Extract author name — only for person authors (type='profile'), not company pages."""
    author = post.get("author", {})
    if isinstance(author, dict) and author.get("type") == "profile":
        return author.get("name")
    return None


def _get_author_linkedin(post: dict) -> Optional[str]:
    """Extract author LinkedIn URL — only for person authors (type='profile')."""
    author = post.get("author", {})
    if isinstance(author, dict) and author.get("type") == "profile":
        return author.get("linkedinUrl")
    return None


def _extract_requirements(description: str) -> list[str]:
    """Heuristic extraction of bullet-point requirements from job description text."""
    if not description:
        return []
    lines = re.split(r"[\n•\-\*]", description)
    return [
        line.strip()
        for line in lines
        if 20 < len(line.strip()) < 200
    ][:8]
